name: Build and Deploy DocFX

on:
  push:
    branches:
      - master
  workflow_dispatch: 
on:
  push:
    branches:
      - master  # or 'main' if your default branch is main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Match your .NET version

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Restore and Build DocFX
        run: docfx docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
